### ISSUE TITLE
Set time signature

### ISSUE THREAD

**Issue by SameerDalal** [jonestristand/react-native-metronome-module#2]
Hello,
I am working on an app, and this library would be really useful. I was wondering though, how can I set or change the time signature of the metronome?

**Comment by jonestristand** [comment]
Do you mean change the frequency of the metronome (the number of beats per minute)?

**Comment by SameerDalal** [comment]
I don't mean changing the beats per minute. By changing the time signature I mean to change the number of beats that are in a measure.

**Comment by SameerDalal** [comment]
By measure I mean a unit of time corresponding to a number of beats at a particular BPM.

**Comment by jonestristand** [comment]
Ah I understand. At the moment this library just plays one sound at a specified frequency, so there's no way at the moment to tell one measure from another. If this was a feature you'd like to add I'd be happy to accept a pull request!

**Comment by SameerDalal** [comment]
I appreciate your help! Do you know any other libraries that do have this feature? If not, I would love to develop it although it might take me a fair bit of time as I am new to developing libraries and react in general, but I will surely send a pull request if I do make it!

**Comment by jonestristand** [comment]
I do not, and particularly do not know of any that work on both android and iOS, which is why I wrote this library :-)

**Comment by SameerDalal** [comment]
Thanks!
